image:
  repository: mcr.microsoft.com/oss/cilium/cilium
  tag: 1.12.5
  digest: ""
  useDigest: false

operator:
  image:
    repository: mcr.microsoft.com/oss/cilium/operator
    tag: 1.12.5
    suffix: ""
    digest: ""
    useDigest: false

ipam:
  mode: "delegated-plugin"

tunnel: disabled

endpointRoutes:
  enabled: true

extraArgs:
  - --local-router-ipv4=169.254.23.0

# kubenet pod CIDR
ipv4NativeRoutingCIDR: 10.241.0.0/16
enableIPv4Masquerade: false
install-no-conntrack-iptables-rules: false
installIptablesRules: true
l7Proxy: false
hubble:
  enabled: false
kubeProxyReplacement: strict

endpointHealthChecking:
  enabled: false

cni:
  install: true
  customConf: true
