FROM ubuntu:14.04.3

# Install dependencies.
RUN apt-get update && apt-get install -y ebtables

# Create plugins directory.
RUN mkdir -p /run/docker/plugins

# Install plugin.
COPY ./out/azure-cnm-plugin /usr/bin
WORKDIR /usr/bin

CMD ["/usr/bin/azure-cnm-plugin"]
