FROM golang:1.7.4

RUN go get -d golang.org/x/sys/unix
RUN go get -d github.com/containernetworking/cni/pkg/skel

COPY . /go/src/github.com/Azure/azure-container-networking

WORKDIR /go/src/github.com/Azure/azure-container-networking
