parameters:
  name: ""
  displayName: ""
  pipelineBuildImage: "$(BUILD_IMAGE)"
  testDropgz: ""
  clusterName: ""
  osSku: ""
stages:
  - stage: ${{ parameters.name }}
    displayName: E2E - ${{ parameters.displayName }}
    dependsOn: 
    - setup
    - publish
    variables:
      TAG: $[ stagedependencies.setup.env.outputs['EnvironmentalVariables.Tag'] ]
      CURRENT_VERSION: $[ stagedependencies.containerize.check_tag.outputs['CurrentTagManifests.currentTagManifests'] ]
    condition: and(succeeded(), eq(variables.TAG, variables.CURRENT_VERSION))
    jobs:
      - job: ${{ parameters.name }}
        displayName: Singletenancy AKS Swift Suite - (${{ parameters.name }})
        timeoutInMinutes: 120
        pool:
          name: $(BUILD_POOL_NAME_DEFAULT)
          demands: 
          - agent.os -equals Linux
          - Role -equals $(CUSTOM_E2E_ROLE)
        variables:
          GOPATH: "$(Agent.TempDirectory)/go" # Go workspace path
          GOBIN: "$(GOPATH)/bin" # Go binaries path
          modulePath: "$(GOPATH)/src/github.com/Azure/azure-container-networking"
        steps:
          - template: e2e-step-template.yaml
            parameters:
              name: ${{ parameters.name }}
              testDropgz: ${{ parameters.testDropgz }}
              clusterName: ${{ parameters.clusterName }}
              osSku: ${{ parameters.osSku }}
