//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiTenantInfo) DeepCopyInto(out *MultiTenantInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiTenantInfo.
func (in *MultiTenantInfo) DeepCopy() *MultiTenantInfo {
	if in == nil {
		return nil
	}
	out := new(MultiTenantInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiTenantNetworkContainer) DeepCopyInto(out *MultiTenantNetworkContainer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiTenantNetworkContainer.
func (in *MultiTenantNetworkContainer) DeepCopy() *MultiTenantNetworkContainer {
	if in == nil {
		return nil
	}
	out := new(MultiTenantNetworkContainer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MultiTenantNetworkContainer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiTenantNetworkContainerList) DeepCopyInto(out *MultiTenantNetworkContainerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MultiTenantNetworkContainer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiTenantNetworkContainerList.
func (in *MultiTenantNetworkContainerList) DeepCopy() *MultiTenantNetworkContainerList {
	if in == nil {
		return nil
	}
	out := new(MultiTenantNetworkContainerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MultiTenantNetworkContainerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiTenantNetworkContainerSpec) DeepCopyInto(out *MultiTenantNetworkContainerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiTenantNetworkContainerSpec.
func (in *MultiTenantNetworkContainerSpec) DeepCopy() *MultiTenantNetworkContainerSpec {
	if in == nil {
		return nil
	}
	out := new(MultiTenantNetworkContainerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiTenantNetworkContainerStatus) DeepCopyInto(out *MultiTenantNetworkContainerStatus) {
	*out = *in
	out.MultiTenantInfo = in.MultiTenantInfo
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiTenantNetworkContainerStatus.
func (in *MultiTenantNetworkContainerStatus) DeepCopy() *MultiTenantNetworkContainerStatus {
	if in == nil {
		return nil
	}
	out := new(MultiTenantNetworkContainerStatus)
	in.DeepCopyInto(out)
	return out
}
