// autogenerated
//

// Code generated by MockGen. DO NOT EDIT.
// Source: /home/vamsi/workspace/azure-container-networking/npm/pkg/dataplane/types.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dataplane "github.com/Azure/azure-container-networking/npm/pkg/dataplane"
	ipsets "github.com/Azure/azure-container-networking/npm/pkg/dataplane/ipsets"
	policies "github.com/Azure/azure-container-networking/npm/pkg/dataplane/policies"
	util "github.com/Azure/azure-container-networking/npm/util"
	gomock "github.com/golang/mock/gomock"
)

// MockGenericDataplane is a mock of GenericDataplane interface.
type MockGenericDataplane struct {
	ctrl     *gomock.Controller
	recorder *MockGenericDataplaneMockRecorder
}

// MockGenericDataplaneMockRecorder is the mock recorder for MockGenericDataplane.
type MockGenericDataplaneMockRecorder struct {
	mock *MockGenericDataplane
}

// NewMockGenericDataplane creates a new mock instance.
func NewMockGenericDataplane(ctrl *gomock.Controller) *MockGenericDataplane {
	mock := &MockGenericDataplane{ctrl: ctrl}
	mock.recorder = &MockGenericDataplaneMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenericDataplane) EXPECT() *MockGenericDataplaneMockRecorder {
	return m.recorder
}

// AddPolicy mocks base method.
func (m *MockGenericDataplane) AddPolicy(policies *policies.NPMNetworkPolicy) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPolicy", policies)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPolicy indicates an expected call of AddPolicy.
func (mr *MockGenericDataplaneMockRecorder) AddPolicy(policies interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPolicy", reflect.TypeOf((*MockGenericDataplane)(nil).AddPolicy), policies)
}

// AddToLists mocks base method.
func (m *MockGenericDataplane) AddToLists(listMetadatas, setMetadatas []*ipsets.IPSetMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddToLists", listMetadatas, setMetadatas)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddToLists indicates an expected call of AddToLists.
func (mr *MockGenericDataplaneMockRecorder) AddToLists(listMetadatas, setMetadatas interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToLists", reflect.TypeOf((*MockGenericDataplane)(nil).AddToLists), listMetadatas, setMetadatas)
}

// AddToSets mocks base method.
func (m *MockGenericDataplane) AddToSets(setMetadatas []*ipsets.IPSetMetadata, podMetadata *dataplane.PodMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddToSets", setMetadatas, podMetadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddToSets indicates an expected call of AddToSets.
func (mr *MockGenericDataplaneMockRecorder) AddToSets(setMetadatas, podMetadata interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToSets", reflect.TypeOf((*MockGenericDataplane)(nil).AddToSets), setMetadatas, podMetadata)
}

// ApplyDataPlane mocks base method.
func (m *MockGenericDataplane) ApplyDataPlane() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyDataPlane")
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyDataPlane indicates an expected call of ApplyDataPlane.
func (mr *MockGenericDataplaneMockRecorder) ApplyDataPlane() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyDataPlane", reflect.TypeOf((*MockGenericDataplane)(nil).ApplyDataPlane))
}

// BootupDataplane mocks base method.
func (m *MockGenericDataplane) BootupDataplane() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BootupDataplane")
	ret0, _ := ret[0].(error)
	return ret0
}

// BootupDataplane indicates an expected call of BootupDataplane.
func (mr *MockGenericDataplaneMockRecorder) BootupDataplane() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BootupDataplane", reflect.TypeOf((*MockGenericDataplane)(nil).BootupDataplane))
}

// CreateIPSets mocks base method.
func (m *MockGenericDataplane) CreateIPSets(setMetadatas []*ipsets.IPSetMetadata) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateIPSets", setMetadatas)
}

// CreateIPSets indicates an expected call of CreateIPSets.
func (mr *MockGenericDataplaneMockRecorder) CreateIPSets(setMetadatas interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIPSets", reflect.TypeOf((*MockGenericDataplane)(nil).CreateIPSets), setMetadatas)
}

// DeleteIPSet mocks base method.
func (m *MockGenericDataplane) DeleteIPSet(setMetadata *ipsets.IPSetMetadata, deleteOption util.DeleteOption) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteIPSet", setMetadata, deleteOption)
}

// DeleteIPSet indicates an expected call of DeleteIPSet.
func (mr *MockGenericDataplaneMockRecorder) DeleteIPSet(setMetadata, deleteOption interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIPSet", reflect.TypeOf((*MockGenericDataplane)(nil).DeleteIPSet), setMetadata, deleteOption)
}

// GetAllIPSets mocks base method.
func (m *MockGenericDataplane) GetAllIPSets() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllIPSets")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetAllIPSets indicates an expected call of GetAllIPSets.
func (mr *MockGenericDataplaneMockRecorder) GetAllIPSets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllIPSets", reflect.TypeOf((*MockGenericDataplane)(nil).GetAllIPSets))
}

// GetAllPolicies mocks base method.
func (m *MockGenericDataplane) GetAllPolicies() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPolicies")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetAllPolicies indicates an expected call of GetAllPolicies.
func (mr *MockGenericDataplaneMockRecorder) GetAllPolicies() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPolicies", reflect.TypeOf((*MockGenericDataplane)(nil).GetAllPolicies))
}

// GetIPSet mocks base method.
func (m *MockGenericDataplane) GetIPSet(setName string) *ipsets.IPSet {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIPSet", setName)
	ret0, _ := ret[0].(*ipsets.IPSet)
	return ret0
}

// GetIPSet indicates an expected call of GetIPSet.
func (mr *MockGenericDataplaneMockRecorder) GetIPSet(setName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIPSet", reflect.TypeOf((*MockGenericDataplane)(nil).GetIPSet), setName)
}

// RemoveFromList mocks base method.
func (m *MockGenericDataplane) RemoveFromList(listMetadata *ipsets.IPSetMetadata, setMetadatas []*ipsets.IPSetMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFromList", listMetadata, setMetadatas)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFromList indicates an expected call of RemoveFromList.
func (mr *MockGenericDataplaneMockRecorder) RemoveFromList(listMetadata, setMetadatas interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFromList", reflect.TypeOf((*MockGenericDataplane)(nil).RemoveFromList), listMetadata, setMetadatas)
}

// RemoveFromSets mocks base method.
func (m *MockGenericDataplane) RemoveFromSets(setMetadatas []*ipsets.IPSetMetadata, podMetadata *dataplane.PodMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFromSets", setMetadatas, podMetadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFromSets indicates an expected call of RemoveFromSets.
func (mr *MockGenericDataplaneMockRecorder) RemoveFromSets(setMetadatas, podMetadata interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFromSets", reflect.TypeOf((*MockGenericDataplane)(nil).RemoveFromSets), setMetadatas, podMetadata)
}

// RemovePolicy mocks base method.
func (m *MockGenericDataplane) RemovePolicy(PolicyKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemovePolicy", PolicyKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemovePolicy indicates an expected call of RemovePolicy.
func (mr *MockGenericDataplaneMockRecorder) RemovePolicy(PolicyKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePolicy", reflect.TypeOf((*MockGenericDataplane)(nil).RemovePolicy), PolicyKey)
}

// RunPeriodicTasks mocks base method.
func (m *MockGenericDataplane) RunPeriodicTasks() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RunPeriodicTasks")
}

// RunPeriodicTasks indicates an expected call of RunPeriodicTasks.
func (mr *MockGenericDataplaneMockRecorder) RunPeriodicTasks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunPeriodicTasks", reflect.TypeOf((*MockGenericDataplane)(nil).RunPeriodicTasks))
}

// UpdatePolicy mocks base method.
func (m *MockGenericDataplane) UpdatePolicy(policies *policies.NPMNetworkPolicy) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePolicy", policies)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePolicy indicates an expected call of UpdatePolicy.
func (mr *MockGenericDataplaneMockRecorder) UpdatePolicy(policies interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePolicy", reflect.TypeOf((*MockGenericDataplane)(nil).UpdatePolicy), policies)
}
