pr:
  branches:
    include:
      - master

trigger:
  branches:
    include:
      - master

stages:
  - stage: build_and_test
    displayName: Build and Unit Test
    jobs:
      - job: unit_tests
        displayName: CNI, NPM, CNS, CNM
        pool:
          name: Networking-ContainerNetworking
          demands: 
          - agent.os -equals Linux
          - Role -equals Build

        container:
          image: "$(BUILD_IMAGE)" # build image set as variable in pipeline runtime for flexibility
          options: "--privileged"

        # Go setup for the vmImage:
        # https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/linux/scripts/installers/go.sh
        variables:
          GOBIN: "$(GOPATH)/bin" # Go binaries path
          GOPATH: "$(System.DefaultWorkingDirectory)/gopath" # Go workspace path
          modulePath: "$(GOPATH)/src/github.com/Azure/azure-container-networking" # $(build.repository.name)' # Path to the module's code

        steps:
          - bash: |
              echo $UID
              sudo rm -rf $(System.DefaultWorkingDirectory)/*
              sudo rm /run/docker/plugins/test.sock || true
              sudo ip link del dev dummy || true
            displayName: "Set up OS environment"

          - checkout: self

          - bash: |
              go version
              go env
              mkdir -p '$(GOBIN)'
              mkdir -p '$(GOPATH)/pkg'
              mkdir -p '$(modulePath)'
              shopt -s extglob
              shopt -s dotglob
              mv !(gopath) '$(modulePath)'
              echo '##vso[task.prependpath]$(GOBIN)'
              echo '##vso[task.prependpath]$(GOROOT)/bin'
            name: "GoEnv"
            displayName: "Set up the Go environment"

          - script: |
              BUILD_NUMBER=$(Build.BuildNumber)
              echo "##vso[task.setvariable variable=StorageID;isOutput=true]$(echo ${BUILD_NUMBER//./-})"
              echo "##vso[task.setvariable variable=CommitHash;isOutput=true]$(git rev-parse HEAD)"
              echo "##vso[task.setvariable variable=Tag;isOutput=true]$(git describe --tags --always --dirty)"
              echo "##vso[task.setvariable variable=ImageTag;isOutput=true]$(git describe --tags --always --dirty)-test"
            workingDirectory: "$(modulePath)"
            name: "EnvironmentalVariables"
            displayName: "Set environmental variables"
            condition: always()

          - script: |
              go get github.com/docker/libnetwork/driverapi
              go get github.com/gorilla/mux
              go get github.com/jstemmer/go-junit-report
              go get github.com/axw/gocov/gocov
              go get github.com/AlekSi/gocov-xml
              go get github.com/matm/gocov-html
              go get github.com/rakyll/gotest
            workingDirectory: "$(modulePath)"
            name: "GoDependencies"
            displayName: "Install Go dependencies"

          - script: |
              export GOOS=windows
              make all-binaries VERSION=$(EnvironmentalVariables.Tag)
            workingDirectory: "$(modulePath)"
            name: "BuildWindows"
            displayName: "Build Windows"

          - script: |
              export GOOS=linux
              make all-binaries VERSION=$(EnvironmentalVariables.Tag)
            workingDirectory: "$(modulePath)"
            name: "BuildLinux"
            displayName: "Build Linux"

          - bash: |
              # run test, echo exit status code to fd 3, pipe output from test to tee, which splits output to stdout and go-junit-report (which converts test output to report.xml), stdout from tee is redirected to fd 4. Take output written to fd 3 (which is the exit code of test), redirect to stdout, pipe to read from stdout then exit with that status code. Read all output from fd 4 (output from tee) and write to top stdout
              { { { { 
                    sudo -E env "PATH=$PATH" make test-all; 
                    echo $? >&3; 
                    } | tee >(go-junit-report > report.xml) >&4; 
                  } 3>&1; 
                } | { read xs; exit $xs; } 
              } 4>&1
            workingDirectory: "$(modulePath)"
            name: "Test"
            displayName: "Run Tests"

          - script: |
              sudo make tools-images VERSION=$(EnvironmentalVariables.Tag)
              sudo make all-images VERSION=$(EnvironmentalVariables.Tag)
            workingDirectory: "$(modulePath)"
            name: "BuildImages"
            displayName: "Build Images"

          - bash: |
              export CODECOV_TOKEN=$(CODECOV_TOKEN)
              bash <(curl -s https://codecov.io/bash)
              gocov convert coverage.out > coverage.json
              gocov-xml < coverage.json > coverage.xml
            workingDirectory: "$(modulePath)"
            name: "Coverage"
            displayName: "Generate Coverage Reports"
            condition: always()

          - script: |
              echo '$(DOCKER_PASSWORD)' | docker login $IMAGE_REGISTRY -u '$(DOCKER_USERNAME)' --password-stdin
              docker tag $IMAGE_REGISTRY/azure-npm:$(EnvironmentalVariables.Tag) $IMAGE_REGISTRY/azure-npm:$(EnvironmentalVariables.Tag)-test
              docker push $IMAGE_REGISTRY/azure-npm:$(EnvironmentalVariables.Tag)-test

              docker tag $IMAGE_REGISTRY/azure-cns:$(EnvironmentalVariables.Tag) $IMAGE_REGISTRY/azure-cns:$(EnvironmentalVariables.Tag)-test
              docker push $IMAGE_REGISTRY/azure-cns:$(EnvironmentalVariables.Tag)-test

              docker tag $IMAGE_REGISTRY/azure-cni-manager:$(EnvironmentalVariables.Tag) $IMAGE_REGISTRY/azure-cni-manager:$(EnvironmentalVariables.Tag)-test
              docker push $IMAGE_REGISTRY/azure-cni-manager:$(EnvironmentalVariables.Tag)-test

              function auto-retry()
              {
                  export i="1"
                  export attempts="300"
                  false
                  while [[ $? -ne 0 ]] && [[ $i -lt $attempts ]]; do
                    printf "Attempt $i/$attempts - " && "$@" && break ||  sleep 3 &&  i=$[$i+1] && false
                  done
              }

              auto-retry docker pull $IMAGE_REGISTRY/azure-npm:$(EnvironmentalVariables.Tag)-test
              auto-retry docker pull $IMAGE_REGISTRY/azure-cns:$(EnvironmentalVariables.Tag)-test
              auto-retry docker pull $IMAGE_REGISTRY/azure-cni-manager:$(EnvironmentalVariables.Tag)-test
            workingDirectory: "$(modulePath)"
            name: "mcrreplication"
            displayName: "Push NPM Image and Wait for Repository"

          - script: |
              cd ./output 
              sudo find . -mindepth 2 -type f -regextype posix-extended ! -iregex '.*\.(zip|tgz)$' -delete
              sudo find . -mindepth 2 -type f -print -exec mv {} . \;
              sudo rm -R -- */ && cd ..
            workingDirectory: "$(modulePath)"
            name: "PrepareArtifacts"
            displayName: "Prepare Artifacts"

          - task: PublishTestResults@2
            inputs:
              testRunner: JUnit
              testResultsFiles: $(modulePath)/report.xml
            displayName: "Publish Test Results"
            condition: always()

          - task: PublishCodeCoverageResults@1
            inputs:
              codeCoverageTool: Cobertura
              summaryFileLocation: $(modulePath)/coverage.xml
            displayName: "Publish Code Coverage Results"
            condition: always()

          - task: CopyFiles@2
            inputs:
              sourceFolder: "$(modulePath)/output"
              targetFolder: $(Build.ArtifactStagingDirectory)
            condition: succeeded()

          - task: PublishBuildArtifacts@1
            inputs:
              artifactName: "output"
              pathtoPublish: "$(Build.ArtifactStagingDirectory)"
            condition: succeeded()

          - publish: $(modulePath)/test/apimodels/
            artifact: clusterdefinitions

          - task: AzureCLI@1
            inputs:
              azureSubscription: $(ARTIFACT_SUBSCRIPTION)
              scriptLocation: "inlineScript"
              inlineScript: |
                echo Creating storage container with name acn-$(EnvironmentalVariables.StorageID) and account name $(STORAGE_ACCOUNT_NAME)
                az storage container create -n acn-$(EnvironmentalVariables.StorageID) --account-name $(STORAGE_ACCOUNT_NAME) --public-access container
                az storage blob upload-batch -d acn-$(EnvironmentalVariables.StorageID) -s ./output/  --account-name $(STORAGE_ACCOUNT_NAME)
              workingDirectory: "$(modulePath)"
            displayName: Create artifact storage container
            condition: succeeded()

  - template: singletenancy/aks-swift/e2e-job-template.yaml
    parameters:
      name: "aks_on_swift_e2e"
      displayName: AKS on Swift
      pipelineBuildImage: "$(BUILD_IMAGE)"

  - template: singletenancy/aks-engine/e2e-job-template.yaml
    parameters:
      name: "ubuntu_16_04_linux_e2e"
      displayName: Ubuntu 16.04
      pipelineBuildImage: "$(BUILD_IMAGE)"
      clusterDefinition: "cniLinux1604.json"
      clusterDefinitionCniTypeKey: "azureCNIURLLinux"
      clusterDefinitionCniBuildOS: "linux"
      clusterDefinitionCniBuildExt: ".tgz"

  - template: singletenancy/aks-engine/e2e-job-template.yaml
    parameters:
      name: "ubuntu_18_04_linux_e2e"
      displayName: Ubuntu 18.04
      pipelineBuildImage: "$(BUILD_IMAGE)"
      clusterDefinition: "cniLinux1804.json"
      clusterDefinitionCniTypeKey: "azureCNIURLLinux"
      clusterDefinitionCniBuildOS: "linux"
      clusterDefinitionCniBuildExt: ".tgz"

  - template: singletenancy/aks-engine/e2e-job-template.yaml
    parameters:
      name: "windows_19_03_e2e"
      displayName: "Windows 1903"
      pipelineBuildImage: "$(BUILD_IMAGE)"
      clusterDefinition: "cniWindows1903.json"
      clusterDefinitionCniTypeKey: "azureCNIURLWindows"
      clusterDefinitionCniBuildOS: "windows"
      clusterDefinitionCniBuildExt: ".zip"

  - stage: cleanup
    displayName: Cleanup
    dependsOn:
      - "aks_on_swift_e2e"
      - "ubuntu_16_04_linux_e2e"
      - "ubuntu_18_04_linux_e2e"
      - "windows_19_03_e2e"
    jobs:
      - job: delete_remote_artifacts
        displayName: Delete remote artifacts
        pool:
          name: Networking-ContainerNetworking
          demands: agent.os -equals Linux
        container:
          image: "$(BUILD_IMAGE)"
        steps:
          - checkout: none
          - task: AzureCLI@1
            inputs:
              azureSubscription: $(ARTIFACT_SUBSCRIPTION)
              scriptLocation: "inlineScript"
              inlineScript: |
                BUILD_NUMBER=$(Build.BuildNumber)
                BUILD_NUMBER=${BUILD_NUMBER//./-}
                echo Deleting storage container with name acn-$BUILD_NUMBER and account name $(STORAGE_ACCOUNT_NAME)
                az storage container delete -n acn-$BUILD_NUMBER --account-name $(STORAGE_ACCOUNT_NAME)
                echo Pruning old docker images...
                sudo docker system prune -f
              workingDirectory: "$(modulePath)"
            displayName: Cleanup remote Azure storage container
